services:
  frontend-pc:
    build:
      context: .
      args:
        - NEXT_PUBLIC_API_URL=/api
        - BACKEND_URL=${BACKEND_URL:-http://localhost:8080}
    container_name: famed-frontend
    restart: unless-stopped
    ports:
      - "5498:3001" # Puerto externo:interno (accede en http://localhost:3000)
    environment:
      NODE_ENV: production
      BACKEND_URL: ${BACKEND_URL:-http://localhost:8080}
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:8080}
